baseurl = "/"
languageCode = "en-us"
title = "A. Brown Blogdown Website"
theme = "blackburn"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Shown in the side menu
copyright = "&copy; 2020. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    DateForm = "2.1.2006"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.
  
  # my stuff
  github = "alexb523"
  linkedin = "alexander-brown-b93aa029"
  stackoverflow = "6816930"



