---
title: About Me and The Blog
author: A. Brown
date: '2020-08-01'
slug: about-me-and-the-blog
categories:
  - R
tags:
  - blog
  - data
  - data analytics
  - data science
  - random thoughts
  - about
---

# Hi There,

This is my initial post on my blog! I am excited to have a space to share my thoughts, opinions, and data explorations on the internet. I don't do a whole lot of social media like Facebook, Twitter, etc. (Although, I do Snap Chat sometimes with some friends). So this will be a nice way to get what I think is important out there.

# A Little Bit About Me

I have a wife who I enjoy spending time with. We like hiking, camping, biking, kayaking, cooking, exercising, and anything else that will get us outdoors. For example, we have been trying to get into bird watching. My dad is a really avid birder and is showing us the ropes! In addition to all those activities mentioned, I also enjoy playing guitar, coding, and I am trying to get into woodworking.

I am a data analyst and an aspiring data scientist. In my professional life overall, I am on the journey to be well rounded at working with data. I have my masters in business analytics from the University of Iowa. I double majored in supply chain management and economics in my undergrad from the University of Northern Iowa.

# A Little About This Blog

I am hoping I can use this blog for a few things:

1. To just document my thoughts about life and stuff in general. Maybe that's something nobody is interested in, but I think it will be helpful for me and maybe the spillover will be of help or interest to other people.

2. *Show off* my coding skills. I learn a lot about coding from the internet and would love to contribute back. Not to mention, if I can point to some data topics and a website in general, I think it could impress prospective employers. The main programs I code in are `R`, `Python`, `SQL` (or `PostgreSQL`) and Excel. I would say I am a heavy `R` user, I am fluent in `Python`, and I am good at `SQL` (querying, setting up databases, giving access, etc.). I am also embarrassingly good at Excel. I hope to produce some posts in all of these languages and maybe even in some languages I learn later on in my journey.
    a. I say I am embarrassingly good at Excel, because ever since I started working out of my undergrad, I have enjoyed working with data. I thought everyone else in the company I worked for was good at Excel and I needed to get good at Excel to keep up with them. It turns out they were not good at Excel and I soon became known for my Excel skills. I became fascinated by the ability to automate and do things fast! The natural progression from that is coding which I was exposed to in my masters and learned mostly on my own from there.

Anyways, I look forward to this and hope to work on it a little every week!

Cheers, A. Brown
